name: Update YouTube Trending Data

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Ambil Data JSON dari Yewtube (Bypass 403)
        run: |
          curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "https://yewtu.be/api/v1/trending?region=ID" -o trending.json

      - name: Simpan dan Push Perubahan ke GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add trending.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update data trending otomatis" && git push)
